language: php

php:
  - 7.1

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - cp .env.travis .env
  - mysql -e 'create database `header-checker-rest`;'
  - composer self-update
  - composer install --no-interaction

script:
  - composer validate --strict
  - vendor/bin/phpunit --coverage-text
