language: php
sudo: false
dist: trusty

php:
  - 7.1

services:
  - mysql

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - cp .env.travis .env
  - mysql -e 'CREATE DATABASE IF NOT EXISTS `xebia_header_checker`;'
  - composer install --no-interaction

script:
  - composer validate --strict
  - vendor/bin/security-checker security:check --end-point=https://security.sensiolabs.org/check_lock
  - vendor/bin/phpunit --coverage-text
